### PR TITLE
move to objc

### PR DESCRIPTION
**Pull request by long1eu**

### CODE REVIEW

**Comment by long1eu** [comment]
I've already done the geolocator. But I forgot about this. :D

**Comment by mvanbeusekom** [comment]
@long1eu, sorry I made a mistake. Turns out the .lock files do belong under source control. I should have looked into this before asking you to remove them. Could you revert commit d996a46? (really sorry)

**Comment by long1eu** [comment]
Let me know when you publish the permission handler and this package so I
can push the geolocalor.

**Comment by mvanbeusekom** [comment]
Both packages have been release ;)

**Comment by long1eu** [comment]
Thanks!

**Comment by mvanbeusekom** [comment]
@long1eu you mentioned you also moved the geolocator plugin from Swift to Objective-C (https://github.com/BaseflowIT/flutter-google-api-availability/pull/13#issuecomment-465582273).

We would love to merge these changes but you haven't created a pull-request yet. Any specific reason why?

**Comment by long1eu** [comment]
I'll create it right now

**Comment by mvanbeusekom** [comment]
@long1eu please check, we just had a new PR (https://github.com/BaseflowIT/flutter-geolocator/pull/230) which would be nice if it is also included in your (new) version.

**Comment by long1eu** [comment]
Ok, sure

**Comment by mvanbeusekom** [comment]
@long1eu, sorry about all the confusion but I have some questions regarding the heading implementation in the above mentioned pull-request so I have reverted the code for now. Maybe you also have some ideas about it and you can have a better implementation in your Objective-C implementation. 

Otherwise maybe just leave it out for now (again apologies for the confusion).

**Comment by long1eu** [comment]
No worries.

**Pull request merged**
